### ISSUE TITLE
pyqt cannot be cross-compiled

### ISSUE THREAD

**Issue by Tobias-Fischer** [andfoy/qt-recipe#5]
Just to keep track of this, currently pyqt cannot be cross-compiled for osx-arm64. It compiles fine natively though.

**Comment by andfoy** [comment]
I can take a look at this once webengine is ready

**Comment by andfoy** [comment]
@Tobias-Fischer, after a long struggle, we managed to cross-compile pyqt here: https://github.com/andfoy/qt-recipe/pull/6

**Comment by Tobias-Fischer** [comment]
Oh wow, that's amazing! Well done. Sooo looking forward to seeing all your PRs merged in, thanks a lot for all your hard work.
